Update page
plutoniumpw/landing pull request #38
Opened 2021-09-28 16:43 UTC by Resxt

Added an update page between the Install and Uninstall pages in the sidebar.

This page contains instructions to update the launcher, to check if the installed version is the latest and and to fix the "Failed to check for updates" error

2021-09-28 17:18 UTC, ChxseH commented
LGTM; Will see if any other staff agree with merging. (Game-UI will fix this updating issue, so unsure if we are going to merge this for it to be obsolete in X months)

2021-09-29 10:20 UTC, 3ldor requested changes

2021-09-29 10:20 UTC, 3ldor commented on src/pages/docs/update.md
> +   (Note that the latest version is the one on the right `r2158-r2190` means that the previous version was `r2158` and that the latest version is `r2190`.
Please clarify that r2190 might not be the _current_ latest version.

2021-09-29 10:20 UTC, 3ldor commented on src/pages/docs/update.md
> +If you don't get the updates automatically this probably means that you pinned the Plutonium launcher while it was running.
Perhaps clarify here that "you" should see the updater pop up for a few seconds before the launcher starts if everything is working correctly.

2021-09-29 10:20 UTC, 3ldor commented on src/pages/docs/update.md
> +3. Pin `plutonium.exe` to your taskbar/start menu and start it
The "fix" is not dependent on pinning the executable, but if any file should be pinned it would indeed be the updater.

2021-10-01 10:31 UTC, 3ldor approved these changes
Likely to be obsolete and removed in the future as Chase said, but can be merged for now.

2021-10-01 10:37 UTC, merged