Update fastdl.md
plutoniumpw/landing pull request #64
Opened 2022-01-11 08:39 UTC by Mythical-Github

webserver mime type info

2022-01-11 13:20 UTC, ChxseH requested changes

2022-01-11 13:20 UTC, ChxseH commented on src/pages/docs/server/t4/fastdl.md
> +For some web servers it is neccesary to add the following mime types if they don't already exist\
What web servers need this? I've never ran across one that needs modifying.

2022-01-11 13:20 UTC, ChxseH commented on src/pages/docs/server/t4/fastdl.md
> +Notes:\
Why are you escaping everything here? Make it into a bulleted list please.

2022-01-11 13:20 UTC, ChxseH commented on src/pages/docs/server/t4/fastdl.md
> +1. Setup any form of Web Server. (wamp, xamp, & iss all have been confirmed to work)
This is a bad change. We will get flooded with "What's the best one to pick out of this list" They can google it and figure it out themselves. All web servers are "confirmed" to work, as long as you can access and click on the files in the directory.

2022-01-11 14:31 UTC, ChxseH reviewed
Also please make sure you change [IW5's FastDL](https://github.com/plutoniumpw/landing/edit/develop/src/pages/docs/server/iw5/fastdl.md) as well.

2022-01-12 07:52 UTC, Mythical-Github commented on src/pages/docs/server/t4/fastdl.md
> +For some web servers it is neccesary to add the following mime types if they don't already exist\
ISS needs it, think it's part of why people can't use hfs and abyss as well, Otherwise certain files like .ff were not downloadable by the client resulting in the client getting an .ff not found error

2022-01-12 08:06 UTC, Mythical-Github commented
aight made the changes, think it's good to go

2022-01-12 16:17 UTC, merged